[package]
name = "trashcan"
version = "0.1.0"
authors = ["derrickturk <dwt@terminusdatascience.com>"]

[dependencies.nom]
version = "^2.1"
features = ["verbose-errors"]

[[bin]]
doc = false
name = "tcc"
